POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZhbGVudGluIiwiaWQiOiI2MjQ4OGRmMTRiNWY4NzQ4MDQ0Njk1ZjciLCJpYXQiOjE2NDg5OTEwOTQsImV4cCI6MTY0ODk5NDY5NH0.J6bcxu9XGZGr-abI088eJew4G_3IyHyRpRRW0WGvXJs

{
  "title": "Vales Blog",
  "author": "Vale",
  "url": "http://wohnblog.de",
  "likes": 0
}

###
GET http://localhost:3003/api/blogs

###
PUT http://localhost:3003/api/blogs/62404eea69c7815f882ffd3f
Content-Type: application/json

{ 
  "likes":13 
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "valentin",
  "name": "Valentin Dietrich",
  "password": "dietrich"
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "hsa",
  "name": "Arto Hellas",
  "password": "greece"
}


###
GET http://localhost:3003/api/users


###
POST http://localhost:3003/api/login 
Content-Type: application/json

{
  "username": "valentin",
  "password": "dietrich"
}

###
DELETE http://localhost:3003/api/blogs/62499b86476bbc413d0e05f4
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZhbGVudGluIiwiaWQiOiI2MjQ4OGRmMTRiNWY4NzQ4MDQ0Njk1ZjciLCJpYXQiOjE2NDg5OTExMzQsImV4cCI6MTY0ODk5NDczNH0.t9ZfmJER1SXoDn0FQtcJZPRf9CT_OmZPSsFuC1bv2Yw
